# Generated by Django 5.0.4 on 2024-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.BinaryField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.BinaryField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.BinaryField(),
        ),
    ]
