# Generated by Django 5.0.4 on 2024-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_email_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.TextField(),
        ),
    ]
